#!/bin/bash

# script that prevents you from making terrible mistakes deleting useful files
# it moves the arguments to the /tmp directory
# you can add an alias in ~/.bash_aliases or ~/.bashrc to overwrite the usual 'rm' command behaviour
# to delete files permanently you can directly use the command rm with sudo 
# or by executing the command providing the path

if [ $# = 0 ]; then
        echo "Usage: rm <file(s)>"
        exit 1
fi

for i in "$@"
do
	name=$(basename "$i")
	count=$(ls /tmp | grep "$name" -c)
	if [ $count -gt 0 ]; then
		mv "$i" "/tmp/${name}-${count}"
	else
		mv "$i" "/tmp/${name}"
	fi
done
