#!/bin/bash

# just a script to hide files and direcotries faster

if [ $# = 0 ]; then
	echo "Usage: hide <file(s)>"
	exit 1
fi

for i in "$@"
do
	if [ -f "$i" -o -d "$i" ]; then
		base=$(basename $i)
		dir=$(dirname $i)
		case $base in 
			.*)
				echo "Element $i already hidden"
				;;
			*)
				#echo "$i ==> $dir/.$base"  
				mv "$i" "$dir/.$base"
				;;
		esac
	else
		echo "$i: no such file or directory"
	fi
done	
