#!/bin/bash

# this script is used to remove all spaces in file names
# it makes life easier if scripts or programs have to operate using those names

for i in *
do
	if [[ "$i" == *\ * ]]; then
		case $i in
			*-*)
				mv "$i" `tr -d " " <<< "$i"`
				;;
			*)
				mv "$i" `tr " " "_" <<< "$i"`
				;;
		esac
	fi
done

